### ISSUE TITLE
How to use with xmonad and termite

### ISSUE THREAD

**Issue by jonascj** [ebranlard/vim-matlab-behave#8]
Great work, this is really cool.
I'm using xmonad as window manager and termite as terminal emulator (with matlab running with -nodesktop). Two modifications were required to make your plugin work with this setup.

## Make xmonad ewmh aware
Include the Ewmh package from contrib in your xmonad config: http://hackage.haskell.org/package/xmonad-contrib-0.13/docs/XMonad-Hooks-EwmhDesktops.html

## termite (matlab in the terminal)
Use the ```-t``` switch to set the wm_name of the termite window such that wmctrl can find it (```-t "MATLAB R"``` or change the ```g:matlab_behave_window_name``` variable in your .vimrc)

Pasting from the selection clipboard (used by xclip in this plugin) you need ```let g:matlab_behave_paste_cmd = 'ctrl+shift+v'``` in .vimrc.

**Comment by ebranlard** [comment]
Thanks a lot for your comment, I guess we could add this to the README if others are interested, for now I'll keep this open.
